---
title: "People"
---

#PI

I obtained my Ph.D in bioscience engineering (Ghent university) and afterwards did a postoc at the Netherlands institute of ecology (NIOO) on marine food web studies. I gained academic independence in 2013 and started a lab on basic community and ecosystem ecology. I often use chemical pollutants as experimental agents to manipulate plankton in controlled microcosms, and use theoretical ecology to gain mechanistic insight from the resulting data. 

#PhD students

* Mark Holmes
* Camille Carpentier
* Oluwafemi Olusoji, a.k.a. Daniel (in collaboration with Marc Aerts, University of Wageningen)
* Helene Voahanginirina 
* Jurg Spaak
* Zhao Qinghua (in collaboration with Paul van den Brink, University of Wageningen)
* Tessa de Bruyn (in collaboration with Nicolas Schtickzelle, University of Louvain)

#Postdocs

* Javier Jarillo Diaz
* Thomas Parmentier (in collaboration with Dries Bonte, Ghent university)

#Alumni

* Karel Viaene
* Jan Baert
* Devdutt Kulkarni
* Jonathan De Raedt
* Wouter Reyns



